service: todo-api

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  stage: ${env:STAGE,'local'}

functions:
  todo:
    handler: handler.root
    events:
      - http:
          path: "{proxy+}"
          method: any

package:
  exclude:
    - node_modules/**

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-prune-plugin
  - serverless-dotenv-plugin

custom:
  prune:
    automatic: true
    number: 3
  serverless-offline:
    httpPort: 3000
