name: Deploy to Stg

on:
  pull_request:
    branches: [ staging ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn test
      env:
        CI: true

  deploy:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --production
    - run: yarn deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        STAGE: staging
        LEANCLOUD_APP_ID: wvpfMzH4o4DE11yx0WKIdb1K-gzGzoHsz
        LEANCLOUD_APP_KEY: myGbvH7Y59jOB6gB90n9MDx5
        LEANCLOUD_APP_MASTER_KEY: bIeA3WrqAWc9b5dN3queQCq9
        SERVER_URL: https://wvpfmzh4.lc-cn-n1-shared.com
